### ISSUE TITLE
node_redis warning when switched from kue

### ISSUE THREAD

**Issue by Deadly0** [lykmapipo/kue-scheduler#57]
This warning appears after installing `kue-scheduler`
```node_redis: Deprecated: The HDEL command contains a "undefined" argument.
This is converted to a "undefined" string now and will return an error from v.3.0 on.
Please handle this in your code to make sure everything works as you intended it to.```

**Comment by lykmapipo** [comment]
Fixed in v0.6.3.

**Comment by Roost** [comment]
@lykmapipo I'm still seeing this error while running v0.6.3. Any ideas why?

**Comment by rfranczyk** [comment]
I am also seeing this error on 0.6.3

**Comment by mohammadrezaprw** [comment]
It seems not fixed yet!

**Comment by hfreire** [comment]
@lykmapipo is it possible that the culprit might be in kue-unique dependency?

**Comment by gmcnaught** [comment]
Yes, very likely the issue is related to kue-unique here:
https://github.com/lykmapipo/kue-unique/blob/master/index.js#L124

So what I don't have a full view here is what steps you took to cause this?
It seems like we can just wrap this with an if (key !== undefined) { } and
call it done?

**Comment by IvanMMM** [comment]
Same for me. 0.6.5

**Comment by mmarshak** [comment]
I am getting also this error when I try to delete the job. Any update on this?

**Comment by IvanMMM** [comment]
There is a pull request in unique repo. Use it.

**Comment by mmarshak** [comment]
@IvanMMM do you mean request -  #25. It seems it is merge almost a year ago?

**Comment by IvanMMM** [comment]
@mmarshak, nope. I mean https://github.com/lykmapipo/kue-unique/pull/7

**Comment by mmarshak** [comment]
Thanks, this fix works. However I deploy my server in AWS and they run pm install, which will override the changes. I wish it was part of the official release.

**Comment by adin234** [comment]
@mmarshak you can update your `package.json` to use the fork.

https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

```
"kue-unique" : "adin234/kue-unique#e6f045b092"
```

**Comment by mmarshak** [comment]
@adin234 thank you for the reference to the fork, however my npm dependency is of kue-scheduler, and not direct dependency of kue-unique. Therefore I will need also to fork kue-scheduler to in order to change its package.json to point to your fork.

**Comment by JuanKaram** [comment]
I'm experiencing the same issue, would be possible to reopen this issue until lykmapipo/kue-unique#7 is merged and a new version of kue-scheduler is released?
